#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/own_files/my_*; do
  [ -r "$rcfile" ] && source "$rcfile"
done

bindkey "^R" history-incremental-search-backward

